<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.27.1" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="NAudio.Lame" Version="2.1.0" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="YoutubeExplode" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hookline.NowPlaying\Hookline.NowPlaying.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
